dashbase:
  baseDir: ../../../index

  cluster:
    name: dashbase-example
    url: localhost:2181

  firehose:
    params:
      file: "../data/nginx.json"
      numReplications: 1000000 
    type: file

  indexer:
    maxIndexingDelayInSec: 30

  retention:
    numDays: 0.007

  parser:
    type: json
    params:
      pattern:
        timeFormat: now
        schema:
          - name: "@timestamp"
            type: time
          - name: host
            type: meta
          - name: request
            type: text
          - name: response
            type: meta
          - name: bytesSent
            type: numeric
          - name: error
            type: meta
          - name: msg
            type: text
          - name: level
            type: meta
          - name: agent
            type: text

server:
  applicationConnectors:
  - type: http
    port: ${PORT} 
  adminConnectors:
  - type: http
    port: ${ADMINPORT} 

logging:
  level: INFO
  appenders:
      - type: file
        currentLogFilename: ../../../logs/dashbase.log
        archive: true
        archivedLogFilenamePattern: ../../../logs/dashbase-%d.log
        archivedFileCount: 9
        timeZone: UTC
